sops:
    pgp:
    - fp: 85D77543B3D624B63CEA9E6DBC17301B491B3F21

creation_rules:
  - path_regex: "overlay/secret.yaml"
    encrypted_regex: "^(data|stringData)$"
    pgp: "FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4"
  # - path_regex: \.enc\.yaml$
  #   encrypted_regex: "^(data|stringData)$"
  #   pgp: "FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4"
  # - path_regex: \.all\.yaml$
  #   pgp: "FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4"
  # - path_regex: \.dev\.yaml$
  #   encrypted_regex: "^(data|stringData)$"
  #   pgp: "FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4"
  # - path_regex: \.uat\.yaml$
  #   pgp: "FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4"
